<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\Signatures\Exit.html" />
    <None Include="wwwroot\sampletemplates\Onboarding.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DinkToPdf" Version="1.0.8" />
    <PackageReference Include="DinkToPdfCopy" Version="1.0.0" />
    <PackageReference Include="EPPlus" Version="6.2.1" />
    <PackageReference Include="Google.Apis.Auth" Version="1.60.0" />
    <PackageReference Include="Google.Apis.Gmail.v1" Version="1.60.0.3056" />
    <PackageReference Include="MailKit" Version="1.18.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.54.1" />
    <PackageReference Include="Microsoft.Office.Interop.Excel" Version="15.0.4795.1001" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="PdfSharpCore" Version="1.3.60" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\lineheight\" />
    <Folder Include="wwwroot\TemplateSavedPasswords\" />
    <Folder Include="wwwroot\TemplateSavedPasswords\" />
    <Folder Include="wwwroot\uploads\" />
  </ItemGroup>

</Project>
